### ISSUE TITLE
ctp_verbs_create_endpoint() compilation failure in topic/create_endpoint_at branch

### ISSUE THREAD

**Issue by carns** [CCI/cci#41]
I think this is just a typo.  Line ctp_verbs_api.c:1404 has a call to ctp_verbs_create_endpoint() that I think is supposed to be ctp_verbs_create_endpoint_at().

**Comment by scottatchley** [comment]
Hi Phil,

Thanks! I committed the fix. I may still need to push it.

Scott


________________________________

**Comment by carns** [comment]
bump :+1: 

I've been testing with this change in place and things are working great. If you can push your commit that would be great so that I stay in sync.

**Comment by scottatchley** [comment]
Done!

Thanks!

**Comment by carns** [comment]
Thanks @scottatchley
